sudo: required
language: bash
services: docker

env:
  - BUILD_RUBY_VERSION=2.5
  - BUILD_RUBY_VERSION=2.6

install: true

script:
  - make build

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

deploy:
  provider: script
  script: make push
  on:
    branch: master
