language: bash
services: docker

env:
  - BUILD_RUBY_VERSION=2.5
  - BUILD_RUBY_VERSION=2.6

install: true

script:
  - make build

before_deploy:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

deploy:
  provider: script
  script: make push
  on:
    branch: master
