name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:
    strategy:
      matrix:
        version: [2.5, 2.7, 3.0]
    runs-on: ubuntu-latest
    env:
      DOCKER_BUILDKIT: '1' # to enable persistent docker cache
      BUILD_RUBY_VERSION: ${{ matrix.version }}
    steps:
    - uses: actions/checkout@v2

    - run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
    - run: make build
    - run: make push

